"""Data models for Deep Research system."""
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional, Dict, Any
from enum import Enum


class TaskStatus(Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


class IterationDecision(Enum):
    CONTINUE = "continue"
    FINISH = "finish"


@dataclass
class Source:
    """Represents a web source found during research."""
    url: str
    title: str
    description: str
    task_id: str
    fetched_content: Optional[str] = None
    fetched_at: Optional[datetime] = None


@dataclass
class Chunk:
    """Represents an extracted content chunk from a source."""
    content: str
    source: Source
    relevance_score: float
    extracted_at: datetime
    task_id: str


@dataclass
class ResearchTask:
    """Represents a sub-task generated by the Planner."""
    id: str
    query: str
    priority: int
    status: TaskStatus
    parent_task_id: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.now)
    completed_at: Optional[datetime] = None
    sources_found: List[Source] = field(default_factory=list)
    chunks_extracted: List[Chunk] = field(default_factory=list)


@dataclass
class GapAnalysis:
    """Result of gap analysis when information is insufficient."""
    has_gaps: bool
    missing_aspects: List[str]
    suggested_queries: List[str]
    reasoning: str


@dataclass
class ResearchContext:
    """Maintains the complete state of a research session."""
    original_question: str
    language: str = "English"
    tasks: List[ResearchTask] = field(default_factory=list)
    chunks: List[Chunk] = field(default_factory=list)
    iteration_count: int = 0
    max_iterations: int = 15
    current_depth: int = 0
    max_depth: int = 5
    
    def get_pending_tasks(self) -> List[ResearchTask]:
        """Get all pending tasks sorted by priority."""
        return sorted(
            [t for t in self.tasks if t.status == TaskStatus.PENDING],
            key=lambda x: x.priority
        )
    
    def get_all_completed_chunks(self) -> List[Chunk]:
        """Get all chunks from completed tasks."""
        return self.chunks
    
    def get_task_by_id(self, task_id: str) -> Optional[ResearchTask]:
        """Find a task by its ID."""
        for task in self.tasks:
            if task.id == task_id:
                return task
        return None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert context to dictionary for LLM prompts."""
        return {
            "original_question": self.original_question,
            "language": self.language,
            "total_tasks": len(self.tasks),
            "completed_tasks": len([t for t in self.tasks if t.status == TaskStatus.COMPLETED]),
            "pending_tasks": len(self.get_pending_tasks()),
            "total_chunks": len(self.chunks),
            "iteration": self.iteration_count,
            "max_iterations": self.max_iterations,
            "current_depth": self.current_depth,
        }
